/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f030x8.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void blikac(void);
void tlacitka(void);

uint32_t Tick;

int main(void) {

	RCC->AHBENR |= RCC_AHBENR_GPIOAEN | RCC_AHBENR_GPIOBEN | RCC_AHBENR_GPIOCEN; // enable
	GPIOA->MODER |= GPIO_MODER_MODER4_0; // LED1 = PA4, output
	GPIOB->MODER |= GPIO_MODER_MODER0_0; // LED2 = PB0, output
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR0_0; // S2 = PC0, pullup
	GPIOC->PUPDR |= GPIO_PUPDR_PUPDR1_0; // S1 = PC1, pullup
	RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN;
	SYSCFG->EXTICR[0] |= SYSCFG_EXTICR1_EXTI0_PC; // select PC0 for EXTI0
	EXTI->IMR |= EXTI_IMR_MR0; // mask
	EXTI->FTSR |= EXTI_FTSR_TR0; // trigger on falling edge
	//NVIC_EnableIRQ(EXTI0_1_IRQn); // enable EXTI0_1
	SysTick_Config(8000); // init SysTick timer 8Mhz;

	/**********INFINIT LOOP************/
	for (;;) {
		//blikac();
		tlacitka();

	}

}

void tlacitka(void) {
	static uint16_t debounce1 = 0xFFFF;
	static uint16_t debounce2 = 0xFFFF;
	static uint32_t off_time1 = 0;
	static uint32_t off_time2 = 0;
	static uint32_t delay = 0;

	if (Tick > delay + 5) {
		delay = Tick;
		debounce1 <<= 1;
		debounce2 <<= 1;
		if (GPIOC->IDR & (1 << 1))
			debounce1 |= 0x0001;
		if (debounce1 == 0x8000) {
			off_time1 = Tick + 500;
			GPIOB->BSRR = (1 << 0);
		}
		if (GPIOC->IDR & (1 << 0))
			debounce2 |= 0x0001;
		if (debounce2 == 0x8000) {
			off_time2 = Tick + 2000;
			GPIOA->BSRR = (1 << 4);
		}
	}
	if (Tick > off_time1) {
		GPIOB->BRR = (1 << 0);
	}
	if (Tick > off_time2) {
		GPIOA->BRR = (1 << 4);
	}
}

void EXTI0_1_IRQHandler(void) {
	if (EXTI->PR & EXTI_PR_PR0) { // check line 0 has triggered the IT
		EXTI->PR |= EXTI_PR_PR0; // clear the pending bit
		GPIOB->ODR ^= (1 << 0);
	}
}
void blikac(void) {
	static uint32_t delay;

	if (Tick > delay + 300) {
		GPIOA->ODR ^= (1 << 4);
		delay = Tick;
	}
}
void SysTick_Handler(void) //Make event service of SysTick;
{
	Tick++;
}

